In [9]:
#READING MATCH DATA INTO PANDAS FRAME

import pandas as pd

In [11]:
matches = pd.read_csv("matches.csv", index_col=0)

In [5]:
matches.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
0,2023-08-11,20:00,Premier League,Matchweek 1,Fri,Away,W,3,0,Burnley,...,Match Report,NaN,17.0,8.0,13.9,0.0,0,0,2024,Manchester City
1,2023-08-19,20:00,Premier League,Matchweek 2,Sat,Home,W,1,0,Newcastle Utd,...,Match Report,NaN,14.0,4.0,17.9,0.0,0,0,2024,Manchester City
2,2023-08-27,14:00,Premier League,Matchweek 3,Sun,Away,W,2,1,Sheffield Utd,...,Match Report,NaN,29.0,9.0,17.3,2.0,0,1,2024,Manchester City
3,2023-09-02,15:00,Premier League,Matchweek 4,Sat,Home,W,5,1,Fulham,...,Match Report,NaN,6.0,4.0,14.8,0.0,1,1,2024,Manchester City
4,2023-09-16,15:00,Premier League,Matchweek 5,Sat,Away,W,3,1,West Ham,...,Match Report,NaN,29.0,13.0,16.4,1.0,0,0,2024,Manchester City

In [33]:
#INVESTIGATING FOR MISSING DATA

matches.shape

(1520, 27)

In [9]:
38*20*2

1520

In [13]:
matches ["team"].value_counts()

team
Manchester City             76
Arsenal                     76
Burnley                     76
Luton Town                  76
Nottingham Forest           76
Brentford                   76
Everton                     76
Wolverhampton Wanderers     76
Fulham                      76
Bournemouth                 76
Brighton and Hove Albion    76
Crystal Palace              76
West Ham United             76
Manchester United           76
Newcastle United            76
Chelsea                     76
Tottenham Hotspur           76
Aston Villa                 76
Liverpool                   76
Sheffield United            76
Name: count, dtype: int64

In [15]:
matches["round"].value_counts()

round
Matchweek 1     40
Matchweek 30    40
Matchweek 23    40
Matchweek 24    40
Matchweek 25    40
Matchweek 18    40
Matchweek 26    40
Matchweek 27    40
Matchweek 28    40
Matchweek 31    40
Matchweek 2     40
Matchweek 32    40
Matchweek 33    40
Matchweek 29    40
Matchweek 35    40
Matchweek 36    40
Matchweek 37    40
Matchweek 34    40
Matchweek 22    40
Matchweek 21    40
Matchweek 20    40
Matchweek 19    40
Matchweek 3     40
Matchweek 4     40
Matchweek 5     40
Matchweek 6     40
Matchweek 7     40
Matchweek 8     40
Matchweek 9     40
Matchweek 10    40
Matchweek 11    40
Matchweek 12    40
Matchweek 13    40
Matchweek 14    40
Matchweek 15    40
Matchweek 16    40
Matchweek 17    40
Matchweek 38    40
Name: count, dtype: int64

In [17]:
matches.dtypes

date             object
time             object
comp             object
round            object
day              object
venue            object
result           object
gf                int64
ga                int64
opponent         object
xg              float64
xga             float64
poss            float64
attendance      float64
captain          object
formation        object
referee          object
match report     object
notes           float64
sh              float64
sot             float64
dist            float64
fk              float64
pk                int64
pkatt             int64
season            int64
team             object
dtype: object

In [15]:
#CLEANING DATA FOR MACHINE LEARNING

matches["date"] = pd.to_datetime(matches["date"])

In [23]:
matches.dtypes

date            datetime64[ns]
time                    object
comp                    object
round                   object
day                     object
venue                   object
result                  object
gf                       int64
ga                       int64
opponent                object
xg                     float64
xga                    float64
poss                   float64
attendance             float64
captain                 object
formation               object
referee                 object
match report            object
notes                  float64
sh                     float64
sot                    float64
dist                   float64
fk                     float64
pk                       int64
pkatt                    int64
season                   int64
team                    object
dtype: object

In [17]:
#CREATING PREDICTORS FOR MACHINE LEARNING

#converting catgorical variables into numbers
matches["venue_code"] = matches["venue"].astype("category").cat.codes
matches["opp_code"] = matches["opponent"].astype("category").cat.codes

In [19]:
matches["hour"] = matches["time"].str.replace(":.+", "", regex=True).astype("int")

In [21]:
matches["day_code"] = matches["date"].dt.dayofweek

In [23]:
matches["target"] = (matches["result"] =="W").astype("int")

In [61]:
matches

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
0,2023-08-11,20:00,Premier League,Matchweek 1,Fri,Away,W,3,0,Burnley,...,0.0,0,0,2024,Manchester City,0,5,20,4,1
1,2023-08-19,20:00,Premier League,Matchweek 2,Sat,Home,W,1,0,Newcastle Utd,...,0.0,0,0,2024,Manchester City,1,14,20,5,1
2,2023-08-27,14:00,Premier League,Matchweek 3,Sun,Away,W,2,1,Sheffield Utd,...,2.0,0,1,2024,Manchester City,0,16,14,6,1
3,2023-09-02,15:00,Premier League,Matchweek 4,Sat,Home,W,5,1,Fulham,...,0.0,1,1,2024,Manchester City,1,9,15,5,1
4,2023-09-16,15:00,Premier League,Matchweek 5,Sat,Away,W,3,1,West Ham,...,1.0,0,0,2024,Manchester City,0,18,15,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1515,2024-04-24,20:00,Premier League,Matchweek 29,Wed,Away,L,2,4,Manchester Utd,...,1.0,0,0,2023,Sheffield United,0,13,20,2,0
1516,2024-04-27,15:00,Premier League,Matchweek 35,Sat,Away,L,1,5,Newcastle Utd,...,0.0,0,0,2023,Sheffield United,0,14,15,5,0
1517,2024-05-04,15:00,Premier League,Matchweek 36,Sat,Home,L,1,3,Nott'ham Forest,...,0.0,1,1,2023,Sheffield United,1,15,15,5,0
1518,2024-05-11,15:00,Premier League,Matchweek 37,Sat,Away,L,0,1,Everton,...,0.0,0,0,2023,Sheffield United,0,8,15,5,0
1519,2024-05-19,16:00,Premier League,Matchweek 38,Sun,Home,L,0,3,Tottenham,...,1.0,0,0,2023,Sheffield United,1,17,16,6,0

In [25]:
#CREATING INITIAL MACHINE LEARNING MODEL
#Training the model

from sklearn.ensemble import RandomForestClassifier

In [26]:
rf = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)

In [27]:
#Splitting up the Training Model and Training Test data

train = matches[matches["date"] < '2024-01-01']

In [28]:
test = matches[matches["date"] > '2024-01-01']

In [29]:
predictors = ["venue_code", "opp_code", "hour", "day_code"]

In [30]:
rf.fit(train[predictors], train["target"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [31]:
preds = rf.predict(test[predictors])

In [39]:
#DETERMINING THE ACCURACY OF THE MODEL

from sklearn.metrics import accuracy_score

In [41]:
acc = accuracy_score(test["target"], preds)

In [43]:
acc

0.6038251366120219

In [45]:
combined = pd.DataFrame(dict(actual=test["target"], prediction=preds), index=test.index)

In [47]:
pd.crosstab(index=combined["actual"], columns=combined["prediction"])

prediction    0    1
actual
0           304  154
1           136  138

In [49]:
from sklearn.metrics import precision_score

In [51]:
precision_score(test["target"], preds)

0.4726027397260274

In [53]:
#IMPROVING PRECISION WITH ROLLING AVERAGES

grouped_matches = matches.groupby("team")

In [55]:
group = grouped_matches.get_group("Manchester City")

In [244]:
group

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
0,2023-08-11,20:00,Premier League,Matchweek 1,Fri,Away,W,3,0,Burnley,...,0.0,0,0,2024,Manchester City,0,5,20,4,1
1,2023-08-19,20:00,Premier League,Matchweek 2,Sat,Home,W,1,0,Newcastle Utd,...,0.0,0,0,2024,Manchester City,1,14,20,5,1
2,2023-08-27,14:00,Premier League,Matchweek 3,Sun,Away,W,2,1,Sheffield Utd,...,2.0,0,1,2024,Manchester City,0,16,14,6,1
3,2023-09-02,15:00,Premier League,Matchweek 4,Sat,Home,W,5,1,Fulham,...,0.0,1,1,2024,Manchester City,1,9,15,5,1
4,2023-09-16,15:00,Premier League,Matchweek 5,Sat,Away,W,3,1,West Ham,...,1.0,0,0,2024,Manchester City,0,18,15,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
793,2024-04-28,16:30,Premier League,Matchweek 35,Sun,Away,W,2,0,Nott'ham Forest,...,1.0,0,0,2023,Manchester City,0,15,16,6,1
794,2024-05-04,17:30,Premier League,Matchweek 36,Sat,Home,W,5,1,Wolves,...,0.0,2,2,2023,Manchester City,1,19,17,5,1
795,2024-05-11,12:30,Premier League,Matchweek 37,Sat,Away,W,4,0,Fulham,...,0.0,1,1,2023,Manchester City,0,9,12,5,1
796,2024-05-14,20:00,Premier League,Matchweek 34,Tue,Away,W,2,0,Tottenham,...,0.0,1,1,2023,Manchester City,0,17,20,1,1
797,2024-05-19,16:00,Premier League,Matchweek 38,Sun,Home,W,3,1,West Ham,...,2.0,0,0,2023,Manchester City,1,18,16,6,1

In [57]:
def rolling_average(group, cols, new_cols):
    group = group.sort_values("date")
    rolling_stats = group[cols].rolling(3, closed='left').mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols)
    return group

In [59]:
cols = ["gf", "ga", "sh", "sot", "dist", "fk", "pk", "pkatt"]
new_cols = [f"{c}_rolling" for c in cols]

In [250]:
new_cols

['gf_rolling',
 'ga_rolling',
 'sh_rolling',
 'sot_rolling',
 'dist_rolling',
 'fk_rolling',
 'pk_rolling',
 'pkatt_rolling']

In [252]:
rolling_average(group, cols, new_cols)

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
761,2023-08-19,20:00,Premier League,Matchweek 2,Sat,Home,W,1,0,Newcastle Utd,...,5,1,2.333333,0.000000,16.000000,6.666667,15.233333,0.000000,0.000000,0.000000
2,2023-08-27,14:00,Premier League,Matchweek 3,Sun,Away,W,2,1,Sheffield Utd,...,6,1,1.666667,0.000000,15.000000,5.333333,16.566667,0.000000,0.000000,0.000000
762,2023-08-27,14:00,Premier League,Matchweek 3,Sun,Away,W,2,1,Sheffield Utd,...,6,1,1.333333,0.333333,19.000000,5.666667,17.700000,0.666667,0.000000,0.333333
3,2023-09-02,15:00,Premier League,Matchweek 4,Sat,Home,W,5,1,Fulham,...,5,1,1.666667,0.666667,24.000000,7.333333,17.500000,1.333333,0.000000,0.666667
763,2023-09-02,15:00,Premier League,Matchweek 4,Sat,Home,W,5,1,Fulham,...,5,1,3.000000,1.000000,21.333333,7.333333,16.466667,1.333333,0.333333,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35,2024-05-11,12:30,Premier League,Matchweek 37,Sat,Away,W,4,0,Fulham,...,5,1,4.666667,0.666667,17.000000,9.333333,16.066667,0.000000,1.666667,1.666667
796,2024-05-14,20:00,Premier League,Matchweek 34,Tue,Away,W,2,0,Tottenham,...,1,1,4.333333,0.333333,16.000000,8.666667,16.833333,0.000000,1.333333,1.333333
36,2024-05-14,20:00,Premier League,Matchweek 34,Tue,Away,W,2,0,Tottenham,...,1,1,3.333333,0.000000,12.333333,6.666667,16.566667,0.000000,1.000000,1.000000
37,2024-05-19,16:00,Premier League,Matchweek 38,Sun,Home,W,3,1,West Ham,...,6,1,2.666667,0.000000,9.666667,5.333333,15.533333,0.000000,1.000000,1.000000
797,2024-05-19,16:00,Premier League,Matchweek 38,Sun,Home,W,3,1,West Ham,...,6,1,2.333333,0.333333,14.000000,6.666667,15.633333,0.666667,0.666667,0.666667

In [61]:
matches_rolling = matches.groupby("team").apply(lambda x: rolling_average(x, cols, new_cols))

C:\Users\Kathir\AppData\Local\Temp\ipykernel_9344\315798404.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  matches_rolling = matches.groupby("team").apply(lambda x: rolling_average(x, cols, new_cols))

In [63]:
matches_rolling = matches_rolling.droplevel('team')

In [65]:
matches_rolling.index = range(matches_rolling.shape[0])

In [182]:
matches_rolling

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
0,2023-08-21,20:00,Premier League,Matchweek 2,Mon,Away,W,1,0,Crystal Palace,...,0,1,1.666667,0.666667,14.333333,5.333333,18.200000,0.000000,0.333333,0.333333
1,2023-08-26,15:00,Premier League,Matchweek 3,Sat,Home,D,2,2,Fulham,...,5,0,1.333333,0.333333,13.666667,3.666667,17.300000,0.000000,0.666667,0.666667
2,2023-08-26,15:00,Premier League,Matchweek 3,Sat,Home,D,2,2,Fulham,...,5,0,1.333333,0.666667,14.666667,4.333333,15.533333,0.000000,1.000000,1.000000
3,2023-09-03,16:30,Premier League,Matchweek 4,Sun,Home,W,3,1,Manchester Utd,...,6,1,1.666667,1.333333,16.333333,6.666667,14.666667,0.000000,1.000000,1.000000
4,2023-09-03,16:30,Premier League,Matchweek 4,Sun,Home,W,3,1,Manchester Utd,...,6,1,2.333333,1.666667,17.666667,7.666667,14.200000,0.000000,0.666667,0.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,2024-05-04,17:30,Premier League,Matchweek 36,Sat,Away,L,1,5,Manchester City,...,5,0,1.666667,2.333333,9.333333,3.666667,15.533333,0.000000,0.000000,0.000000
1456,2024-05-11,15:00,Premier League,Matchweek 37,Sat,Home,L,1,3,Crystal Palace,...,5,0,1.333333,3.666667,5.666667,2.333333,12.266667,0.000000,0.000000,0.000000
1457,2024-05-11,15:00,Premier League,Matchweek 37,Sat,Home,L,1,3,Crystal Palace,...,5,0,1.000000,4.333333,6.000000,3.333333,10.866667,0.000000,0.000000,0.000000
1458,2024-05-19,16:00,Premier League,Matchweek 38,Sun,Away,L,0,2,Liverpool,...,6,0,1.000000,3.666667,10.000000,5.666667,12.733333,0.000000,0.000000,0.000000
1459,2024-05-19,16:00,Premier League,Matchweek 38,Sun,Away,L,0,2,Liverpool,...,6,0,0.666667,2.666667,10.666667,6.000000,16.066667,0.333333,0.000000,0.000000

In [67]:
#RETRAINING MY MACHINE LEARNING MODEL

def make_predictions(data, predictors):
    train = data[data["date"] < '2024-01-01']
    test = data[data["date"] > '2024-01-01']
    rf.fit(train[predictors], train["target"])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test["target"], predicted=preds), index=test.index)
    precision = precision_score(test["target"], preds)
    return combined, precision

In [75]:
combined, precision = make_predictions(matches_rolling, predictors + new_cols)

In [73]:
precision

'%r'

In [278]:
combined

      actual  predicted
37         1          1
38         1          0
39         1          1
40         1          1
41         1          1
...      ...        ...
1455       0          0
1456       0          1
1457       0          1
1458       0          0
1459       0          0

[732 rows x 2 columns]

In [296]:
combined = combined.merge(matches_rolling[["date", "team", "opponent", "result"]], left_index=True, right_index=True)

In [298]:
combined

,actual,predicted,date,team,opponent,result
37,1,1,2024-01-20,Arsenal,Crystal Palace,W
38,1,0,2024-01-20,Arsenal,Crystal Palace,W
39,1,1,2024-01-30,Arsenal,Nott'ham Forest,W
40,1,1,2024-01-30,Arsenal,Nott'ham Forest,W
41,1,1,2024-02-04,Arsenal,Liverpool,W
...,...,...,...,...,...,...
1455,0,0,2024-05-04,Wolverhampton Wanderers,Manchester City,L
1456,0,1,2024-05-11,Wolverhampton Wanderers,Crystal Palace,L
1457,0,1,2024-05-11,Wolverhampton Wanderers,Crystal Palace,L
1458,0,0,2024-05-19,Wolverhampton Wanderers,Liverpool,L
1459,0,0,2024-05-19,Wolverhampton Wanderers,Liverpool,L

In [307]:
class MissingDict(dict):
    __missing__= lambda self, key: key

map_values = {
    "Brighton and Hove Albion":"Brighton",
    "Manchester United": "Manchester Utd",
    "Newcastle United": "Newcastle Utd",
    "Tottenham Hotspur": "Tottenham",
    "Westham United": "West Ham",
    "Wolverhampton Wanderers": "Wolves"
}
mapping = MissingDict(**map_values)

In [311]:
mapping["Manchester United"]

'Manchester Utd'

In [315]:
combined["new_team"] = combined["team"].map(mapping)

In [317]:
combined

,actual,predicted,date,team,opponent,result,new_team
37,1,1,2024-01-20,Arsenal,Crystal Palace,W,Arsenal
38,1,0,2024-01-20,Arsenal,Crystal Palace,W,Arsenal
39,1,1,2024-01-30,Arsenal,Nott'ham Forest,W,Arsenal
40,1,1,2024-01-30,Arsenal,Nott'ham Forest,W,Arsenal
41,1,1,2024-02-04,Arsenal,Liverpool,W,Arsenal
...,...,...,...,...,...,...,...
1455,0,0,2024-05-04,Wolverhampton Wanderers,Manchester City,L,Wolves
1456,0,1,2024-05-11,Wolverhampton Wanderers,Crystal Palace,L,Wolves
1457,0,1,2024-05-11,Wolverhampton Wanderers,Crystal Palace,L,Wolves
1458,0,0,2024-05-19,Wolverhampton Wanderers,Liverpool,L,Wolves
1459,0,0,2024-05-19,Wolverhampton Wanderers,Liverpool,L,Wolves

In [319]:
merged = combined.merge(combined, left_on=["date", "new_team"], right_on=["date", "opponent"])

In [321]:
merged

,actual_x,predicted_x,date,team_x,opponent_x,result_x,new_team_x,actual_y,predicted_y,team_y,opponent_y,result_y,new_team_y
0,1,1,2024-01-20,Arsenal,Crystal Palace,W,Arsenal,0,0,Crystal Palace,Arsenal,L,Crystal Palace
1,1,1,2024-01-20,Arsenal,Crystal Palace,W,Arsenal,0,0,Crystal Palace,Arsenal,L,Crystal Palace
2,1,0,2024-01-20,Arsenal,Crystal Palace,W,Arsenal,0,0,Crystal Palace,Arsenal,L,Crystal Palace
3,1,0,2024-01-20,Arsenal,Crystal Palace,W,Arsenal,0,0,Crystal Palace,Arsenal,L,Crystal Palace
4,1,1,2024-01-30,Arsenal,Nott'ham Forest,W,Arsenal,0,0,Nottingham Forest,Arsenal,L,Nottingham Forest
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1239,0,1,2024-05-11,Wolverhampton Wanderers,Crystal Palace,L,Wolves,1,0,Crystal Palace,Wolves,W,Crystal Palace
1240,0,0,2024-05-19,Wolverhampton Wanderers,Liverpool,L,Wolves,1,0,Liverpool,Wolves,W,Liverpool
1241,0,0,2024-05-19,Wolverhampton Wanderers,Liverpool,L,Wolves,1,1,Liverpool,Wolves,W,Liverpool
1242,0,0,2024-05-19,Wolverhampton Wanderers,Liverpool,L,Wolves,1,0,Liverpool,Wolves,W,Liverpool
1243,0,0,2024-05-19,Wolverhampton Wanderers,Liverpool,L,Wolves,1,1,Liverpool,Wolves,W,Liverpool

In [323]:
merged[(merged["predicted_x"] == 1) &  (merged["predicted_y"] ==0)]["actual_x"].value_counts()

actual_x
1    187
0    128
Name: count, dtype: int64

In [325]:
187+128

315

In [327]:
187/315

0.5936507936507937